SRC_TOP:=../../..
include $(SRC_TOP)/Makefile.inc

DEPS = CommissionEmployee.h \
	   BasePlusCommissionEmployee.h

OBJ = main.o \
	  CommissionEmployee.o \
	  BasePlusCommissionEmployee.o

include $(SRC_TOP)/Makefile.rules
