SRC_TOP:=.
include $(SRC_TOP)/rules/Makefile.inc

SUBDIRS = \
	10.Operator_Overloading_Class_string \
	11.Object-Oriented_Programming-Inheritance \
	12.Object_oriented_programming-Polymorphism \
	13.Stream_IO_A_Deeper_Look

include $(SRC_TOP)/rules/Makefile.dir
