SRC_TOP:=../../..
include $(SRC_TOP)/Makefile.inc

DEPS = \
	Account.h \
	SavingsAccount.h \
	CheckingAccount.h

OBJ = \
	main.o \
	Account.o \
	SavingsAccount.o \
	CheckingAccount.o

include $(SRC_TOP)/Makefile.rules
